namespace TeamProject01.Gameplay
{
    public enum GameplaySfxCue
    {
        None = 0,
        Fire = 1,
        FireStart = 2,
        Hit = 3,
        Explosion = 4,
        RollHit = 5,
        Activation = 6,
        Pickup = 7,
        GoodPickup = 8,
        Open = 9,
        ShieldBreak = 10,
        ResultClear = 11,
        ResultGameOver = 12,
        MeteorCast = 13,
        HudSkill2 = 14,
        FireLoop = 15,
        ManaOrbPickup = 16,
        ShieldHit = 17,
        ShieldRegenStart = 18,
        NexusHeal = 19,
        HudSkill3LoopA = 20,
        HudSkill3LoopB = 21,
        BossTeleport = 22,
        BossDiamondCharge = 23,
        BossDiamondLaunch = 24,
        BossDiamondBurstLarge = 25,
        BossDiamondBurstSmall = 26,
        BossJumpImpact = 27,
        BossDeath = 28,
        MonsterDeath = 30,
        MonsterJumpLanding = 31,
        MonsterSuicideExplosion = 32,
        MonsterSlowZoneCast = 33,
        MonsterRangedFire = 34,
        MonsterSegmentCutCast = 35,
        MonsterSegmentCutLaunch = 36,
        MonsterObstacleSummon = 37,
        MonsterMeleeImpact = 38,
        MonsterShieldLoop = 39,
        MonsterPortalTeleport = 40
    }
}
